site_name: 勿怯 勿惰 勿贪 勿我
nav:
  - 个人首页: "index.md"
  - 工具链接网址: "about.md"
  - '数学':
    - 数学: "数学/math.md"
    - 微积分: "数学/caculus.md"
  - '编程语言':
    - "C语言":
      - C: "编程语言/c/c.md"
    - "C++语言":
      - C++: "编程语言/cpp/cpp.md"
  - '数据结构':
    - 总述: "数据结构/dsa.md"
  - '操作系统':
    - 总述: "操作系统/os.md"
  - '计算机组成原理':
    - 总述: "计算机组成原理/jz.md"
  - '计算机网络':
    - 总述: "计算机网络/jw.md"



theme:
  name: material